apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
  labels:
    service-type: public
spec:
  selector:
    app: jupyterhub
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
