apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: "1234"

---

apiVersion: v1
kind: Secret
metadata:
  name: jupyter-secret
type: Opaque
stringData:
  user: "stepan_prokhorov"
  password: "123456"

